FROM golang

WORKDIR /go/src/github.com/sethwklein/slackinviter
COPY . .
RUN GOPATH=/go go get .

# SLACKINVITER_PORT
# SLACKINVITER_CAPTCHASITEKEY
# SLACKINVITER_CAPTCHASECRET
# SLACKINVITER_SLACKTOKEN

CMD ["slackinviter"]
